Prefecturesearch.create(name:'北海道', prefecture_id:'2')
Prefecturesearch.create(name:'青森県', prefecture_id:'3')
Prefecturesearch.create(name:'岩手県', prefecture_id:'4')
#Camppostsearch.create(name:'北海道', category_id:'1')
#Camppostsearch.create(name:'青森県', category_id:'2')
#Camppostsearch.create(name:'岩手県', category_id:'3')

#Category.create(name:'北海道')
#Category.create(name:'青森県')
#Category.create(name:'岩手県')
#Camppostsearch.create(name:'北海道', category_id:'1')
#Camppostsearch.create(name:'青森県', category_id:'2')
#Camppostsearch.create(name:'岩手県', category_id:'3')
